global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'yuvraj.mist@gmail.com'
  smtp_auth_username: 'yuvraj.mist@gmail.com'
  smtp_auth_password_file: /run/secrets/alertmanager_smtp_password
  smtp_require_tls: true

route:
  receiver: default
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: default
    webhook_configs:
      - url: 'http://api:8000/api/alertmanager/webhook'
    email_configs:
      - to: 'yuvraj.mist@gmail.com'

