
version: '3.8'

services:
  redis:
    image: redis:7
    env_file: .env
    command: >
      sh -c "redis-server --save 900 1 --save 300 10 --save 60 10000 
             --loglevel notice --maxmemory 256mb --maxmemory-policy allkeys-lru
             --bind 0.0.0.0
             --disable-command-security-warnings yes"
    ports:
      - "6379:6379"
    networks:
      - rl-net

  api:
    build:
      context: .
      dockerfile: app/api/Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/home/appuser/app
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_BUCKET=${SUPABASE_BUCKET}
      - SERVICE_NAME=api
      # Sentry removed; logs go to stdout and Promtail ships to Loki
    depends_on:
      - redis
    networks:
      - rl-net
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen(\"http://localhost:8000/health\", timeout=5).status==200 else 1)' "]
      interval: 30s
      timeout: 10s
      retries: 3
    dns:
      - 8.8.8.8
      - 1.1.1.1

  worker:
    build:
      context: .
      dockerfile: app/worker/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
      x-bake:
        # platforms:
        #   - linux/amd64
    command: celery -A app.core.celery.celery_app worker --loglevel=info -P prefork -c 4
    volumes:
      - ./app:/home/appuser/app
      - ./worker:/home/appuser/worker
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY}
      - SUPABASE_BUCKET=${SUPABASE_BUCKET}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - WORKER_METRICS_PORT=9100
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prom_metrics
      - SERVICE_NAME=worker
    depends_on:
      - api
    networks:
      - rl-net
    privileged: true
    user: root
    tmpfs:
      - /tmp/prom_metrics:size=64m
    healthcheck:
      test: ["CMD", "celery", "inspect", "ping", "-A", "app.core.celery"]
      interval: 30s
      timeout: 10s
      retries: 3
    dns:
      - 8.8.8.8
      - 1.1.1.1

  evaluator:
    image: rl-evaluator:latest
    build:
      context: .
      dockerfile: docker/Dockerfile.evaluator
    platform: linux/arm64
    profiles:
      - evaluator

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    command: python /home/appuser/frontend/gradio_app.py
    ports:
      - "7860:7860"
    volumes:
      - ./frontend:/home/appuser/frontend
    environment:
      - API_URL=https://amazing-cleanly-ram.ngrok-free.app
    depends_on:
      - api
    networks:
      - rl-net
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import urllib.request,sys; sys.exit(0 if urllib.request.urlopen(\"http://localhost:7860\", timeout=5).status==200 else 1)' "]
      interval: 30s
      timeout: 10s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=broker:redis:6379:1,default:redis:6379:0
      - HTTP_PORT=8081
      - REDIS_CONNECTION_MODE=direct
      - REDIS_PASSWORD=
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - rl-net

  redis-exporter:
    image: oliver006/redis_exporter:latest
    environment:
      - REDIS_ADDR=redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - rl-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=15d
    ports:
      - "9090:9090"
    depends_on:
      - api
      - worker
    networks:
      - rl-net

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    env_file: .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./scripts/grafana_user_provision.sh:/docker-entrypoint-initgrafana.d/10-create-user.sh:ro
    depends_on:
      - prometheus
      - loki
    networks:
      - rl-net

  grafana-init:
    image: curlimages/curl:8.5.0
    command: sh /init/10-create-user.sh
    env_file: .env
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./scripts/grafana_user_provision.sh:/init/10-create-user.sh:ro
    depends_on:
      - grafana
    networks:
      - rl-net
    restart: "no"
  alertmanager:
    image: prom/alertmanager:latest
    command:
      - --config.file=/etc/alertmanager/config.yml
      - --storage.path=/data
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml:ro
      - alertmanager_data:/data
    ports:
      - "9093:9093"
    networks:
      - rl-net
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:2.9.5
    command: ["-config.file=/etc/loki/config.yml"]
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config.yml:/etc/loki/config.yml:ro
      - loki_data:/loki
    networks:
      - rl-net

  promtail:
    image: grafana/promtail:2.9.5
    command: ["-config.file=/etc/promtail/config.yml"]
    volumes:
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - promtail_positions:/tmp
    networks:
      - rl-net
    depends_on:
      - loki

volumes:
  prometheus_data:
  loki_data:
  promtail_positions:
  alertmanager_data:
  grafana_data:

networks:
  rl-net:
    driver: bridge
