groups:
  - name: service-health
    rules:
      - alert: APITargetDown
        expr: up{job="api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: API target is down
          description: Prometheus cannot scrape the API /metrics endpoint.

      - alert: WorkerTargetDown
        expr: up{job="celery_worker"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Celery worker metrics target is down
          description: Prometheus cannot scrape the worker metrics endpoint.

  - name: rl-quality
    rules:
      - alert: HighEvaluationFailures
        expr: increase(evaluation_failed_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High evaluation failure rate
          description: More than 5 failed evaluations in the last 5 minutes.

      - alert: SlowEvaluationsP95
        expr: histogram_quantile(0.95, sum(rate(evaluation_duration_seconds_bucket[5m])) by (le)) > 60
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Evaluation p95 latency is high
          description: p95 evaluation duration exceeds 60 seconds.

      - alert: LeaderboardLatencyHigh
        expr: rate(leaderboard_query_duration_seconds_sum[5m]) / rate(leaderboard_query_duration_seconds_count[5m]) > 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Leaderboard query latency is high
          description: Average leaderboard query duration exceeds 500ms over 10 minutes.

      - alert: CeleryQueueBacklog
        expr: celery_queue_length{queue_name="celery"} > 50
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Celery queue backlog
          description: Celery queue length is above 50 for 10 minutes.

  - name: infrastructure
    rules:
      - alert: RedisExporterTargetDown
        expr: up{job="redis"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Redis exporter target is down
          description: Prometheus cannot scrape the redis_exporter metrics target.

      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Redis is down
          description: redis_exporter reports the Redis instance is unreachable.

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.9
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Redis memory usage high
          description: Redis memory usage exceeded 90% of the configured maxmemory.

      - alert: RedisEvictions
        expr: increase(redis_evicted_keys_total[5m]) > 0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Redis is evicting keys
          description: Redis evicted keys in the last 5 minutes, likely due to memory pressure.

      - alert: HostCPUHigh
        expr: 100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 90
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Host CPU usage is high
          description: Average CPU utilization across cores exceeded 90% for 10 minutes.

      - alert: HostMemoryHigh
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 90
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Host memory usage is high
          description: Host memory usage exceeded 90% for 10 minutes.

