groups:
  - name: service-health
    rules:
      - alert: APITargetDown
        expr: up{job="api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: API target is down
          description: Prometheus cannot scrape the API /metrics endpoint.

      - alert: WorkerTargetDown
        expr: up{job="celery_worker"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Celery worker metrics target is down
          description: Prometheus cannot scrape the worker metrics endpoint.

  - name: rl-quality
    rules:
      - alert: HighEvaluationFailures
        expr: increase(evaluation_failed_total[5m]) > 5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High evaluation failure rate
          description: More than 5 failed evaluations in the last 5 minutes.

      - alert: SlowEvaluationsP95
        expr: histogram_quantile(0.95, sum(rate(evaluation_duration_seconds_bucket[5m])) by (le)) > 60
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Evaluation p95 latency is high
          description: p95 evaluation duration exceeds 60 seconds.

      - alert: LeaderboardLatencyHigh
        expr: rate(leaderboard_query_duration_seconds_sum[5m]) / rate(leaderboard_query_duration_seconds_count[5m]) > 0.5
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Leaderboard query latency is high
          description: Average leaderboard query duration exceeds 500ms over 10 minutes.

      - alert: CeleryQueueBacklog
        expr: celery_queue_length{queue_name="celery"} > 50
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Celery queue backlog
          description: Celery queue length is above 50 for 10 minutes.

