global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: celery_worker
    static_configs:
      - targets: ['worker:9100']

  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'alertmanager:9093' ]

