global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: celery_worker
    static_configs:
      - targets: ['worker:9100']

  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']

  # - job_name: node
  #   static_configs:
  #     - targets: ['node-exporter:9100']

  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://api:8000/health/simple
          - http://frontend:7860
          - http://prometheus:9090/-/ready
          - http://alertmanager:9093/-/ready
          - http://grafana:3000/login
          - http://loki:3100/ready
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

alerting:
  alertmanagers:
    - static_configs:
        - targets: [ 'alertmanager:9093' ]

