apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
  - name: Postgres
    type: postgres
    access: proxy
    url: db:5432
    database: leaderboard
    user: ${DB_USER}
    secureJsonData:
      password: ${DB_PASSWORD}
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      tlsAuth: false
      tlsAuthWithCACert: false
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400

